# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22c43c03eef2808671bfd89f1396a13e9d61bb6e16b4dcd7d574d6988780e27dd8ced4a887e83151bcbe97f12eb55aecea3c1c453208dc32043fd28be733bc17

test:
  secret_key_base: de2afcc13099e9e321a8f2133bf7880f0353f06145eca82a18696b5ba4260cfdad1b3256416752c8bf48139232291ac22d9abcb2b3522dd70dd2a07a2cb2cde3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
